export const PROJECT_LOAD_SUCCESS = 'PROJECT_LOAD_SUCCESS';
export const PROJECT_LOAD_FAILED = 'PROJECT_LOAD_FAILED';

export const EXPAND_PROJECTS = 'EXPAND_PROJECTS';
export const COLLAPSE_PROJECTS = 'COLLAPSE_PROJECTS';