export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_LANGUAGES = 'ADD_LANGUAGES';
export const REMOVE_TRANSLATION = 'REMOVE_TRANSLATION';
export const EXPAND_PROJECTS = 'EXPAND_PROJECTS';
export const COLLAPSE_PROJECTS = 'COLLAPSE_PROJECTS';